const welcomeTranslations = {
    AF: "خوش آمدید", // Afghanistan (Pashto)
    AL: "Mirësevini", // Albania (Albanian)
    DZ: "أهلاً وسهلاً", // Algeria (Arabic)
    AS: "Afio mai", // American Samoa (Samoan)
    AD: "Benvingut", // Andorra (Catalan)
    AO: "Bem-vindo", // Angola (Portuguese)
    AI: "Welcome", // Anguilla (English)
    AG: "Welcome", // Antigua and Barbuda (English)
    AR: "Bienvenido", // Argentina (Spanish)
    AM: "Բարի գալուստ", // Armenia (Armenian)
    AW: "Bienvenido", // Aruba (Spanish)
    AU: "Welcome", // Australia (English)
    AT: "Willkommen", // Austria (German)
    AZ: "Xoş gəlmisiniz", // Azerbaijan (Azerbaijani)
    BS: "Welcome", // Bahamas (English)
    BH: "أهلاً وسهلاً", // Bahrain (Arabic)
    BD: "স্বাগতম", // Bangladesh (Bengali)
    BB: "Welcome", // Barbados (English)
    BY: "Добро пожаловать", // Belarus (Russian)
    BE: "Welkom", // Belgium (Dutch)
    BZ: "Bienvenidos", // Belize (Spanish)
    BJ: "Bienvenue", // Benin (French)
    BM: "Welcome", // Bermuda (English)
    BT: "བཀའ་འདུལ་བ", // Bhutan (Dzongkha)
    BO: "Bienvenidos", // Bolivia (Spanish)
    BA: "Dobrodošli", // Bosnia and Herzegovina (Bosnian)
    BW: "Dumelang", // Botswana (Setswana)
    BR: "Bem-vindo", // Brazil (Portuguese)
    IO: "Welcome", // British Indian Ocean Territory (English)
    BG: "Добре дошли", // Bulgaria (Bulgarian)
    BF: "Bienvenue", // Burkina Faso (French)
    BI: "Welcome", // Burundi (Kirundi)
    KH: "សូមស្វាគមន៍", // Cambodia (Khmer)
    CM: "Bienvenue", // Cameroon (French)
    CA: "Bienvenue", // Canada (French)
    CV: "Bem-vindo", // Cape Verde (Portuguese)
    KY: "Welcome", // Cayman Islands (English)
    CF: "Bienvenue", // Central African Republic (French)
    TD: "Bienvenue", // Chad (French)
    CL: "Bienvenido", // Chile (Spanish)
    CN: "欢迎", // China (Chinese)
    CO: "Bienvenido", // Colombia (Spanish)
    KM: "Marhaban", // Comoros (Arabic)
    CG: "Bienvenue", // Congo (French)
    CD: "Bienvenue", // Democratic Republic of the Congo (French)
    CK: "Welcome", // Cook Islands (English)
    CR: "Bienvenido", // Costa Rica (Spanish)
    CI: "Bienvenue", // Côte d'Ivoire (French)
    HR: "Dobrodošli", // Croatia (Croatian)
    CU: "Bienvenido", // Cuba (Spanish)
    CW: "Bienvenido", // Curaçao (Spanish)
    CY: "Καλώς ήρθατε", // Cyprus (Greek)
    CZ: "Vítejte", // Czech Republic (Czech)
    DK: "Velkommen", // Denmark (Danish)
    DJ: "Ahlan", // Djibouti (Arabic)
    DM: "Welcome", // Dominica (English)
    DO: "Bienvenido", // Dominican Republic (Spanish)
    EC: "Bienvenido", // Ecuador (Spanish)
    EG: "أهلاً وسهلاً", // Egypt (Arabic)
    SV: "Bienvenido", // El Salvador (Spanish)
    GQ: "Bienvenido", // Equatorial Guinea (Spanish)
    ER: "እንኳን ደህና መጡ", // Eritrea (Tigrinya)
    EE: "Tere tulemast", // Estonia (Estonian)
    ET: "እንኳን ደህና መጡ", // Ethiopia (Amharic)
    FK: "Bienvenidos", // Falkland Islands (Spanish)
    FO: "Velkomin", // Faroe Islands (Faroese)
    FJ: "Bula", // Fiji (Fijian)
    FI: "Tervetuloa", // Finland (Finnish)
    FR: "Bienvenue", // France (French)
    PF: "Bienvenue", // French Polynesia (French)
    GA: "Bienvenue", // Gabon (French)
    GM: "Welcome", // Gambia (English)
    GE: "კეთილი იყოს თქვენი მობრძანება", // Georgia (Georgian)
    DE: "Willkommen", // Germany (German)
    GH: "Akwaaba", // Ghana (Akan)
    GI: "Welcome", // Gibraltar (English)
    GR: "Καλώς ήρθατε", // Greece (Greek)
    GL: "Velkommen", // Greenland (Danish)
    GD: "Welcome", // Grenada (English)
    GU: "Håfa adai", // Guam (Chamorro)
    GT: "Bienvenidos", // Guatemala (Spanish)
    GG: "Welcome", // Guernsey (English)
    GN: "Bienvenue", // Guinea (French)
    GW: "Bem-vindo", // Guinea-Bissau (Portuguese)
    HT: "Bienvenue", // Haiti (French)
    HN: "Bienvenido", // Honduras (Spanish)
    HK: "歡迎", // Hong Kong (Cantonese)
    HU: "Üdvözöljük", // Hungary (Hungarian)
    IS: "Velkomin", // Iceland (Icelandic)
    IN: "स्वागत है", // India (Hindi)
    ID: "Selamat datang", // Indonesia (Indonesian)
    IR: "به شما خوش آمد می گویم", // Iran (Persian)
    IQ: "أهلاً وسهلاً", // Iraq (Arabic)
    IE: "Fáilte", // Ireland (Irish)
    IM: "Welcome", // Isle of Man (English)
    IL: "ברוך הבא", // Israel (Hebrew)
    IT: "Benvenuto", // Italy (Italian)
    JM: "Welcome", // Jamaica (English)
    JP: "ようこそ", // Japan (Japanese)
    JE: "Welcome", // Jersey (English)
    JO: "أهلاً وسهلاً", // Jordan (Arabic)
    KZ: "Қош келдіңіз", // Kazakhstan (Kazakh)
    KE: "Karibu", // Kenya (Swahili)
    KI: "Welcome", // Kiribati (English)
    KP: "환영합니다", // North Korea (Korean)
    KR: "환영합니다", // South Korea (Korean)
    KW: "أهلاً وسهلاً", // Kuwait (Arabic)
    KG: "Кош келиңиз", // Kyrgyzstan (Kyrgyz)
    LA: "ຍິນດີຕ້ອນຮັບ", // Laos (Lao)
    LV: "Laipni lūdzam", // Latvia (Latvian)
    LB: "أهلاً وسهلاً", // Lebanon (Arabic)
    LS: "Khotso", // Lesotho (Sesotho)
    LR: "Welcome", // Liberia (English)
    LY: "أهلاً وسهلاً", // Libya (Arabic)
    LI: "Willkommen", // Liechtenstein (German)
    LT: "Sveiki", // Lithuania (Lithuanian)
    LU: "Willkommen", // Luxembourg (German)
    MO: "歡迎", // Macao (Chinese)
    MK: "Добредојдовте", // Republic of Macedonia (Macedonian)
    MG: "Tongasoa", // Madagascar (Malagasy)
    MW: "Tengani", // Malawi (Chichewa)
    MY: "Selamat datang", // Malaysia (Malay)
    MV: "ޝަން ކޮށްދު", // Maldives (Dhivehi)
    ML: "Bienvenue", // Mali (French)
    MT: "Merħba", // Malta (Maltese)
    MH: "Welkam", // Marshall Islands (Marshallese)
    MQ: "Bienvenue", // Martinique (French)
    MR: "أهلاً وسهلاً", // Mauritania (Arabic)
    MU: "Welcome", // Mauritius (English)
    MX: "Bienvenido", // Mexico (Spanish)
    FM: "Welcome", // Micronesia (English)
    MD: "Bine ați venit", // Republic of Moldova (Romanian)
    MC: "Bienvenue", // Monaco (French)
    MN: "Тавтай морилно уу", // Mongolia (Mongolian)
    ME: "Dobrodošli", // Montenegro (Montenegrin)
    MS: "Welcome", // Montserrat (English)
    MA: "أهلاً وسهلاً", // Morocco (Arabic)
    MZ: "Bem-vindo", // Mozambique (Portuguese)
    MM: "ကြိုဆိုပါသည်", // Myanmar (Burmese)
    NA: "Welcome", // Namibia (English)
    NR: "Welcome", // Nauru (English)
    NP: "स्वागत छ", // Nepal (Nepali)
    NL: "Welkom", // Netherlands (Dutch)
    NZ: "Haere mai", // New Zealand (Māori)
    NI: "Bienvenido", // Nicaragua (Spanish)
    NE: "Bienvenue", // Niger (French)
    NG: "Welcome", // Nigeria (English)
    NU: "Haere mai", // Niue (Māori)
    NF: "Welcome", // Norfolk Island (English)
    MP: "Welcome", // Northern Mariana Islands (English)
    NO: "Velkommen", // Norway (Norwegian)
    OM: "أهلاً وسهلاً", // Oman (Arabic)
    PK: "خوش آمدید", // Pakistan (Urdu)
    PW: "Yokwe", // Palau (Palauan)
    PS: "أهلاً وسهلاً", // Palestinian Territory (Arabic)
    PA: "Bienvenido", // Panama (Spanish)
    PG: "Welcome", // Papua New Guinea (English)
    PY: "Bienvenido", // Paraguay (Spanish)
    PE: "Bienvenido", // Peru (Spanish)
    PH: "Maligayang pagdating", // Philippines (Tagalog)
    PN: "Welcome", // Pitcairn (English)
    PL: "Witamy", // Poland (Polish)
    PT: "Bem-vindo", // Portugal (Portuguese)
    PR: "Bienvenido", // Puerto Rico (Spanish)
    QA: "أهلاً وسهلاً", // Qatar (Arabic)
    RO: "Bun venit", // Romania (Romanian)
    RU: "Добро пожаловать", // Russia (Russian)
    RW: "Murakaza neza", // Rwanda (Kinyarwanda)
    KN: "Welcome", // Saint Kitts and Nevis (English)
    LC: "Welcome", // Saint Lucia (English)
    WS: "Afio mai", // Samoa (Samoan)
    SM: "Benvenuto", // San Marino (Italian)
    ST: "Bem-vindo", // Sao Tome and Principe (Portuguese)
    SA: "أهلاً وسهلاً", // Saudi Arabia (Arabic)
    SN: "Bienvenue", // Senegal (French)
    RS: "Добродошли", // Serbia (Serbian)
    SC: "Bienvenue", // Seychelles (French)
    SL: "Welcome", // Sierra Leone (English)
    SG: "Welcome", // Singapore (English)
    SX: "Bienvenido", // Sint Maarten (Spanish)
    SK: "Vitajte", // Slovakia (Slovak)
    SI: "Dobrodošli", // Slovenia (Slovenian)
    SB: "Welcome", // Solomon Islands (English)
    SO: "Welcome", // Somalia (English)
    ZA: "Welkom", // South Africa (Afrikaans)
    SS: "Welcome", // South Sudan (English)
    ES: "Bienvenido", // Spain (Spanish)
    LK: "ආයුබෝවන්", // Sri Lanka (Sinhala)
    SD: "أهلاً وسهلاً", // Sudan (Arabic)
    SR: "Welkom", // Suriname (Dutch)
    SZ: "Siyakwamukela", // Swaziland (Swazi)
    SE: "Välkommen", // Sweden (Swedish)
    CH: "Willkommen", // Switzerland (German)
    SY: "أهلاً وسهلاً", // Syria (Arabic)
    TW: "歡迎", // Taiwan (Chinese)
    TJ: "Хуш омадед", // Tajikistan (Tajik)
    TZ: "Karibu", // Tanzania (Swahili)
    TH: "ยินดีต้อนรับ", // Thailand (Thai)
    TG: "Bienvenue", // Togo (French)
    TK: "Haere mai", // Tokelau (Māori)
    TO: "Mālō e le lei", // Tonga (Tongan)
    TT: "Welcome", // Trinidad and Tobago (English)
    TN: "أهلاً وسهلاً", // Tunisia (Arabic)
    TR: "Hoş geldiniz", // Turkey (Turkish)
    TM: "Hoş geldiniz", // Turkmenistan (Turkmen)
    TC: "Welcome", // Turks and Caicos Islands (English)
    TV: "Welcome", // Tuvalu (English)
    UG: "Karibu", // Uganda (Swahili)
    UA: "Ласкаво просимо", // Ukraine (Ukrainian)
    AE: "أهلاً وسهلاً", // United Arab Emirates (Arabic)
    GB: "Welcome", // United Kingdom (English)
    US: "Welcome", // United States (English)
    UY: "Bienvenido", // Uruguay (Spanish)
    UZ: "Xush kelibsiz", // Uzbekistan (Uzbek)
    VU: "Welcome", // Vanuatu (English)
    VE: "Bienvenido", // Venezuela (Spanish)
    VN: "Chào mừng", // Vietnam (Vietnamese)
    WF: "Welcome", // Wallis and Futuna (French)
    EH: "أهلاً وسهلاً", // Western Sahara (Arabic)
    YE: "أهلاً وسهلاً", // Yemen (Arabic)
    ZM: "Welcome", // Zambia (English)
    ZW: "Welcome", // Zimbabwe (English)
  };

  export {welcomeTranslations}
  